name: Refresh Update_Site

on:
  workflow_dispatch:

jobs:
  build-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Maven Tycho
        run: mvn clean verify

      - name: Copy update site content to update_site/ (excluding 'repository' level)
        run: |
          rm -rf update_site/*
          repo_dir=$(find sites -type d -path 'sites/*/target/repository' | head -n 1)
          echo "Found repository at: $repo_dir"
          cp -r "$repo_dir"/* update_site/

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check for changes
        id: changes
        run: |
          if [ -n "$(git status --porcelain update_site)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Create branch and push changes if update_site changed
        if: steps.changes.outputs.changed == 'true'
        id: create_branch
        run: |
          BRANCH="update-site-update-$(date +%Y%m%d%H%M%S)"
          git checkout -b "$BRANCH"
          git add update_site
          git commit -m "Update update_site with latest build artifacts"
          git push --set-upstream origin "$BRANCH"
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update update_site with latest build artifacts
          branch: ${{ steps.create_branch.outputs.branch }}
          title: Update update_site directory with latest build artifacts
          body: |
            This PR updates the update_site directory with the latest build artifacts generated by Tycho build.
          base: master
